export { ReactComponent as Account } from './account.svg';
export { ReactComponent as AlertCircleOutline } from './alert-circle-outline.svg';
export { ReactComponent as Check } from './check.svg';
export { ReactComponent as ChevronDown } from './chevron-down.svg';
export { ReactComponent as CloseCircle } from './close-circle.svg';
export { ReactComponent as DotsLoader } from './dots-loader.svg';
export { ReactComponent as Music } from './music.svg';
export { ReactComponent as Play } from './play.svg';
export { ReactComponent as Plus } from './plus.svg';
